#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_VERSION := 0.0.3


PROJECT_NAME := iot_bme280_relais_$(PROJECT_VERSION)

include $(IDF_PATH)/make/project.mk

