CFLAGS += -DBME280_FLOAT_ENABLE

##COMPONENT_ADD_INCLUDEDIRS=./driver
#COMPONENT_ADD_INCLUDEDIRS := ./driver

#COMPONENT_SRCDIRS := ./driver
#COMPONENT_OBJS := ./driver/bme280.o


##
#COMPONENT_SUBMODULES += esp-mqtt
COMPONENT_ADD_INCLUDEDIRS := ./include
COMPONENT_SRCDIRS :=  ./ ./driver
COMPONENT_PRIV_INCLUDEDIRS := ./driver
