#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_VERSION := 0.0.4

PROJECT_NAME := iot_bme280_$(PROJECT_VERSION)

include $(IDF_PATH)/make/project.mk

